//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.05 at 10:38:15 AM GMT 
//

package com.example.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the  package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: 
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SaleEnvelope }
     * 
     */
    public SaleEnvelope createSaleEnvelope() {
        return new SaleEnvelope();
    }

    /**
     * Create an instance of {@link SaleEnvelopeA }
     * 
     */
    public SaleEnvelopeA createSaleEnvelopeA() {
        return new SaleEnvelopeA();
    }

    /**
     * Create an instance of {@link SaleEnvelopeA.SaleListA }
     * 
     */
    public SaleEnvelopeA.SaleListA createSaleEnvelopeASaleListA() {
        return new SaleEnvelopeA.SaleListA();
    }

    /**
     * Create an instance of {@link SaleEnvelopeA.SaleListA.Statement }
     * 
     */
    public SaleEnvelopeA.SaleListA.Statement createSaleEnvelopeASaleListAStatement() {
        return new SaleEnvelopeA.SaleListA.Statement();
    }

    /**
     * Create an instance of {@link SaleEnvelopeA.SaleListA.Statement.Purchases }
     * 
     */
    public SaleEnvelopeA.SaleListA.Statement.Purchases createSaleEnvelopeASaleListAStatementPurchases() {
        return new SaleEnvelopeA.SaleListA.Statement.Purchases();
    }

    /**
     * Create an instance of {@link SaleEnvelope.SaleList }
     * 
     */
    public SaleEnvelope.SaleList createSaleEnvelopeSaleList() {
        return new SaleEnvelope.SaleList();
    }

    /**
     * Create an instance of {@link SaleEnvelope.SaleList.Invoice }
     * 
     */
    public SaleEnvelope.SaleList.Invoice createSaleEnvelopeSaleListInvoice() {
        return new SaleEnvelope.SaleList.Invoice();
    }

    /**
     * Create an instance of {@link SaleEnvelope.Header }
     * 
     */
    public SaleEnvelope.Header createSaleEnvelopeHeader() {
        return new SaleEnvelope.Header();
    }

    /**
     * Create an instance of {@link SaleEnvelope.Trailer }
     * 
     */
    public SaleEnvelope.Trailer createSaleEnvelopeTrailer() {
        return new SaleEnvelope.Trailer();
    }

    /**
     * Create an instance of {@link SaleEnvelopeA.SaleListA.Statement.Customer }
     * 
     */
    public SaleEnvelopeA.SaleListA.Statement.Customer createSaleEnvelopeASaleListAStatementCustomer() {
        return new SaleEnvelopeA.SaleListA.Statement.Customer();
    }

    /**
     * Create an instance of {@link SaleEnvelopeA.SaleListA.Statement.Amount }
     * 
     */
    public SaleEnvelopeA.SaleListA.Statement.Amount createSaleEnvelopeASaleListAStatementAmount() {
        return new SaleEnvelopeA.SaleListA.Statement.Amount();
    }

    /**
     * Create an instance of {@link SaleEnvelopeA.SaleListA.Statement.Purchases.Article }
     * 
     */
    public SaleEnvelopeA.SaleListA.Statement.Purchases.Article createSaleEnvelopeASaleListAStatementPurchasesArticle() {
        return new SaleEnvelopeA.SaleListA.Statement.Purchases.Article();
    }

    /**
     * Create an instance of {@link SaleEnvelope.SaleList.Invoice.Item }
     * 
     */
    public SaleEnvelope.SaleList.Invoice.Item createSaleEnvelopeSaleListInvoiceItem() {
        return new SaleEnvelope.SaleList.Invoice.Item();
    }

}
