//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.05 at 10:38:15 AM GMT 
//

package com.example.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SaleListCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SaleList" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Invoice" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Initial" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2" minOccurs="2"/>
 *                             &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Item" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="3" minOccurs="3"/>
 *                                       &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Balance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Trailer" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CompletionTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "saleList",
    "trailer"
})
@XmlRootElement(name = "SaleEnvelope")
public class SaleEnvelope {

    @XmlElement(name = "Header", required = true)
    protected SaleEnvelope.Header header;
    @XmlElement(name = "SaleList", required = true)
    protected List<SaleEnvelope.SaleList> saleList;
    @XmlElement(name = "Trailer")
    protected SaleEnvelope.Trailer trailer;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link SaleEnvelope.Header }
     *     
     */
    public SaleEnvelope.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link SaleEnvelope.Header }
     *     
     */
    public void setHeader(SaleEnvelope.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the saleList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the saleList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSaleList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SaleEnvelope.SaleList }
     * 
     * 
     */
    public List<SaleEnvelope.SaleList> getSaleList() {
        if (saleList == null) {
            saleList = new ArrayList<SaleEnvelope.SaleList>();
        }
        return this.saleList;
    }

    /**
     * Gets the value of the trailer property.
     * 
     * @return
     *     possible object is
     *     {@link SaleEnvelope.Trailer }
     *     
     */
    public SaleEnvelope.Trailer getTrailer() {
        return trailer;
    }

    /**
     * Sets the value of the trailer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SaleEnvelope.Trailer }
     *     
     */
    public void setTrailer(SaleEnvelope.Trailer value) {
        this.trailer = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SaleListCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "saleListCount"
    })
    public static class Header {

        @XmlElement(name = "SaleListCount", required = true)
        protected String saleListCount;

        /**
         * Gets the value of the saleListCount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSaleListCount() {
            return saleListCount;
        }

        /**
         * Sets the value of the saleListCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSaleListCount(String value) {
            this.saleListCount = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Invoice" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Initial" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2" minOccurs="2"/>
     *                   &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Item" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="3" minOccurs="3"/>
     *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Balance" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "invoice"
    })
    public static class SaleList {

        @XmlElement(name = "Invoice", required = true)
        protected List<SaleEnvelope.SaleList.Invoice> invoice;

        /**
         * Gets the value of the invoice property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the invoice property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInvoice().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SaleEnvelope.SaleList.Invoice }
         * 
         * 
         */
        public List<SaleEnvelope.SaleList.Invoice> getInvoice() {
            if (invoice == null) {
                invoice = new ArrayList<SaleEnvelope.SaleList.Invoice>();
            }
            return this.invoice;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Initial" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2" minOccurs="2"/>
         *         &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Item" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="3" minOccurs="3"/>
         *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Balance" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "initial",
            "surname",
            "item",
            "balance",
            "currency"
        })
        public static class Invoice {

            @XmlElement(name = "Initial", required = true)
            protected List<String> initial;
            @XmlElement(name = "Surname", required = true)
            protected String surname;
            @XmlElement(name = "Item", required = true)
            protected List<SaleEnvelope.SaleList.Invoice.Item> item;
            @XmlElement(name = "Balance")
            protected double balance;
            @XmlElement(name = "Currency")
            protected String currency;

            /**
             * Gets the value of the initial property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the initial property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getInitial().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getInitial() {
                if (initial == null) {
                    initial = new ArrayList<String>();
                }
                return this.initial;
            }

            /**
             * Gets the value of the surname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSurname() {
                return surname;
            }

            /**
             * Sets the value of the surname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSurname(String value) {
                this.surname = value;
            }

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SaleEnvelope.SaleList.Invoice.Item }
             * 
             * 
             */
            public List<SaleEnvelope.SaleList.Invoice.Item> getItem() {
                if (item == null) {
                    item = new ArrayList<SaleEnvelope.SaleList.Invoice.Item>();
                }
                return this.item;
            }

            /**
             * Gets the value of the balance property.
             * 
             */
            public double getBalance() {
                return balance;
            }

            /**
             * Sets the value of the balance property.
             * 
             */
            public void setBalance(double value) {
                this.balance = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="3" minOccurs="3"/>
             *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "code",
                "description",
                "category",
                "price",
                "quantity"
            })
            public static class Item {

                @XmlElement(name = "Code", type = Integer.class)
                protected List<Integer> code;
                @XmlElement(name = "Description", required = true)
                protected String description;
                @XmlElement(name = "Category", required = true)
                protected String category;
                @XmlElement(name = "Price")
                protected double price;
                @XmlElement(name = "Quantity")
                protected int quantity;

                /**
                 * Gets the value of the code property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the code property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCode().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Integer }
                 * 
                 * 
                 */
                public List<Integer> getCode() {
                    if (code == null) {
                        code = new ArrayList<Integer>();
                    }
                    return this.code;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the category property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCategory() {
                    return category;
                }

                /**
                 * Sets the value of the category property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCategory(String value) {
                    this.category = value;
                }

                /**
                 * Gets the value of the price property.
                 * 
                 */
                public double getPrice() {
                    return price;
                }

                /**
                 * Sets the value of the price property.
                 * 
                 */
                public void setPrice(double value) {
                    this.price = value;
                }

                /**
                 * Gets the value of the quantity property.
                 * 
                 */
                public int getQuantity() {
                    return quantity;
                }

                /**
                 * Sets the value of the quantity property.
                 * 
                 */
                public void setQuantity(int value) {
                    this.quantity = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CompletionTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "completionTime"
    })
    public static class Trailer {

        @XmlElement(name = "CompletionTime", required = true)
        protected String completionTime;

        /**
         * Gets the value of the completionTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompletionTime() {
            return completionTime;
        }

        /**
         * Sets the value of the completionTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompletionTime(String value) {
            this.completionTime = value;
        }

    }

}
